---
server:
  port: 8080

proxy:
  servers:
    http:
      port: 9080
      mappings:
       - pattern: /.*
         url: http://localhost:8000
    https:
      ssl: true
      port: 9443
      mappings:
       - pattern: /.*
         url: http://localhost:8000