---
server:
  port: "9900"

proxy:
  servers:
    http:
      port: "9000"
    https:
      ssl: true
      port: "9443"
  mappings:
   - pattern: ${default.pattern:/.*}
     url: ${default.url:http://localhost:8080}
